#!/bin/bash

if [ $# -lt 1 ]
then
        echo "usage: $0 arg"
        exit 1
fi

for i in "$@"
do
        echo $i
        for j in `ps ax | grep $i | awk -F " " '{print $1 " " $5}' | sed s/grep $i$ | cut -f1 -d' '`
        do
                echo $j
                kill -9  $j
        done
done
