/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _XDR_H_RPCGEN
#define _XDR_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct my_struct {
	char *object;
	int fd;
};
typedef struct my_struct my_struct;

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_my_struct (XDR *, my_struct*);

#else /* K&R C */
extern bool_t xdr_my_struct ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_XDR_H_RPCGEN */
